### ISSUE TITLE
captha

### ISSUE THREAD

**Issue by sampathkumar0511** [AcademicsToday/academicstoday-django#163]
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fafe24db730>
Traceback (most recent call last):
  File "/home/normsoftware/project/sampath/lib/python3.5/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/normsoftware/project/sampath/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/home/normsoftware/project/sampath/lib/python3.5/site-packages/django/utils/autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "/home/normsoftware/project/sampath/lib/python3.5/site-packages/django/core/management/__init__.py", line 327, in execute
    autoreload.check_errors(django.setup)()
  File "/home/normsoftware/project/sampath/lib/python3.5/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/normsoftware/project/sampath/lib/python3.5/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/normsoftware/project/sampath/lib/python3.5/site-packages/django/apps/registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "/home/normsoftware/project/sampath/lib/python3.5/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/home/normsoftware/project/sampath/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'captcha'

**Comment by gdsuta** [comment]
Yes I got the same problem, can anyone fix it? I'm a physics teacher and beginner in programming, gonna use this to make website at my school.  Thanks!

**Comment by bartmika** [comment]
Hi @Sebastian-Rydzewski, would it be possible if you could attempt to remove the captcha from the `Django` application? I currently am unable to fix this issue and don't see myself fixing this issue until next month.

**Comment by Sebastian-Rydzewski** [comment]
Hey @bartmika, unfortunately I have my own projects tying down my free time, if I get a chance to take a look at it before you do I'll let you know.  I just can't at this time.

**Comment by bartmika** [comment]
Hi @gdsuta, I've submitted latest code which uses more recent libraries. Can you try installing and see if it fixes the problem? Please make sure you run under the following:

* Python 3.6
* Postgres 10
* Latest PIP
* Latest VirtualEnv

In addition I wrote the following **devops** articles on how to set it up for DigitalOcean.

* https://github.com/AcademicsToday/academicstoday-django/wiki/1-Setup-Project-on-DigitalOcean-CentOS-7

* https://github.com/AcademicsToday/academicstoday-django/wiki/2-CentOS-7-additional-improvements

* https://github.com/AcademicsToday/academicstoday-django/wiki/3-CentOS-7-Backup-and-restore-proceedure

Let me know if it helps!
